apiVersion: v2
appVersion: 2.4.0
description: A Helm chart for Spark on Kubernetes operator.
home: https://github.com/kubeflow/spark-operator
keywords:
- apache spark
- big data
maintainers:
- email: yuchaoran2011@gmail.com
  name: yuchaoran2011
  url: https://github.com/yuchaoran2011
- email: github@chenyicn.net
  name: ChenYi015
  url: https://github.com/ChenYi015
name: spark-operator
version: 2.4.0
